spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: admin
    password: ${DATASOURCE_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database: postgresql
      properties:
        hibernate:
          format_sql: true
  application:
    name: caravan
    jwt:
      keycloak:
        url: ${ISSUER_URI}
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  web:
    error:
      include-message: always

server:
  servlet:
    context-path: '/api-caravan/'
  port: ${PORT}
  address: 0.0.0.0

jwt:
  auth:
    converter:
      resource-id: ${spring.application.jwt.keycloak.client-id}
      principle-attribute: preferred_username

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always
    beans:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true